# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-03-06T04:42:42Z"
  labels:
    app.kubernetes.io/instance: my-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.26.0
    helm.sh/chart: alertmanager-1.8.0
  name: my-prometheus-alertmanager
  namespace: monitoring
  resourceVersion: "402447619"
  uid: 9ffc89bb-08df-42ba-960a-aa11e3b43c28
